site_name: Formation Big Data
site_description: Formation sur les Infrastructures Big Data
site_author: Lilia Sfaxi
site_url: http://liliasfaxi.github.io/formation-bigdata

# Repository
repo_name: liliasfaxi/formation-bigdata
repo_url: https://github.com/liliasfaxi/formation-bigdata

# Copyright
copyright: 'Copyright &copy; 2024 Lilia Sfaxi'

# Theme directory
plugins:
  - search
  - autolink_references:
        autolinks:
            - reference_prefix: AF-
              target_url: https://linear.com/AF-<num>
            - reference_prefix: PROJ-
              target_url: https://jiracloud.com/PROJ-<num> 
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - footnotes
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  favicon: img/favicon.ico
  logo: "img/logo.png"
  palette:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
    primary: Red
    accent: Orange
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/links.css'
social:
  - type: globe
    link: http://liliasfaxi.wix.com/liliasfaxi
  - type: github-alt
    link: https://github.com/liliasfaxi
  - type: twitter
    link: https://twitter.com/lillitou
  - type: linkedin
    link: https://www.linkedin.com/in/liliasfaxi/


# Page tree
pages:
   - Partie 1 - Hadoop HDFS: 'tp1.md'
   - Partie 2 - Hadoop Map Reduce: 'tp2.md'
   - Partie 3 - Spark Shell: 'tp3.md'
   - Partie 4 - Traitement par Lot avec Spark: 'tp4.md'
   - Partie 5 - Traitement Streaming avec Spark: 'tp5.md'


